[package]
name = "simon"
version = "0.1.0"
description = "que se yo"
authors = ["Simon Bierozko <105741786+simon1494@users.noreply.github.com>"]
license = "MIT"
edition = "2024"

[dependencies]
color-eyre = "0.6.3"
crossterm = "0.28.1"
ratatui = "0.29.0"
